#! /bin/sh

# Main update script - it expects only a data directory for output
# Parliament specific options/settings are set in this file (through options passed to update_and_merge.py)

OUTPUT=${1?Missing output directory parameter (data base directory)}

CALLDIR="$(dirname "$(readlink "$0")")"
cd "${CALLDIR}" || { echo "Could not cd to the script directory?!?" ; exit 1 ; }

python3 update_and_merge.py --complete --from-period=20 --retry-count=20 "$OUTPUT"
